version: "3.8"

services:
  front-end:
    build: revature-bookshelf-frontend
    ports:
      - 5010:80
  back-end:
    build: revature-bookshelf-backend
    ports:
      - 5020:8080

  sqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
        - ./:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080

networks:
  default:
    name: bookshelf_network