version: "3.8"

services:

  sqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
        - ./:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
      
networks:
  default:
    name: mysqldb_network