# Server Port
server:
  port: 9001

# JWT secret key for authenticator.utils.JwtUtils
jwt:
  secret-key: "SECRET"
---
# DB Information
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/usersdb
    url: jdbc:mysql://localhost:5000/monoDB
    username: root
    password: rootpass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    activate:
      on-profile: production
